version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=superSecretDBPassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=energyTrack_db
    ports:
      - 5432:5432
    networks:
      - myshared-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  server:
    container_name: enertrack-server
    restart: unless-stopped
    image: enertrack-server:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - myshared-network
    depends_on:
      - db

  client:
    container_name: enertrack-client
    restart: unless-stopped
    image: enertrack-client:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - myshared-network
    depends_on:
      - server

networks:
  myshared-network:

volumes:
  pgdata: {}
